<?php

namespace Atelier\AppointementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AppointementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointementRepository extends EntityRepository
{
  public function getAppointement($nbByPage, $page)
  {
    if ($page < 1) {
      throw new \InvalidArgumentException('The $page argument cannot be less than 1 (value : "'.$page.'").');
    }
 
    $query = $this->createQueryBuilder('a')
                  ->getQuery();
                  
                  
    $query->setFirstResult(($page-1) * $nbByPage)
          ->setMaxResults($nbByPage);
 
    return new Paginator($query);
  }
}
