atelier_category_new:
    pattern:  /new
    defaults: { _controller: AtelierCategoryBundle:Category:new }

atelier_category_disp:
    pattern:  /{id}
    defaults: { _controller: AtelierCategoryBundle:Category:disp }
    requirements:
        id:  \d+
