atelier_category_new:
    pattern:  /new
    defaults: { _controller: AtelierCategoryBundle:Category:new }


atelier_category_edit:
    pattern:  /{id}/edit
    defaults: { _controller: AtelierCategoryBundle:Category:edit }
    requirements:
        id:  \d+

atelier_category_delete:
    pattern:  /{id}/delete
    defaults: { _controller: AtelierCategoryBundle:Category:delete }
    requirements:
        id:  \d+

atelier_category_disp:
    pattern:  /{id}
    defaults: { _controller: AtelierCategoryBundle:Category:disp }
    requirements:
        id:  \d+

atelier_category_index:
    pattern:  /
    defaults: { _controller: AtelierCategoryBundle:Category:dispAll, page: 1 }

atelier_category_dispAll:
    pattern:  /index/{page}
    defaults: { _controller: AtelierCategoryBundle:Category:dispAll, page: 1 }
    requirements:
        page:  \d*
