<?php

namespace Atelier\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	
	public function getCategories($nbByPage, $page)
  {
    if ($page < 1) {
      throw new \InvalidArgumentException('The $page argument cannot be less than 1 (value : "'.$page.'").');
    }
 
    $query = $this->createQueryBuilder('a')
                  ->orderBy('a.name', 'ASC')
                  ->getQuery();
                  
                  
    $query->setFirstResult(($page-1) * $nbByPage)
          ->setMaxResults($nbByPage);
 
    return new Paginator($query);
  }
  	
}
