atelier_product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: AtelierProductBundle:Product:edit }
    requirements:
        id:  \d+

atelier_product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: AtelierProductBundle:Product:delete }
    requirements:
        id:  \d+

atelier_product_disp:
    pattern:  /{id}
    defaults: { _controller: AtelierProductBundle:Product:disp }
    requirements:
        id:  \d+

atelier_product_index:
    pattern:  /
    defaults: { _controller: AtelierProductBundle:Product:dispAll, page: 1 }

atelier_product_dispAll:
    pattern:  /index/{page}
    defaults: { _controller: AtelierProductBundle:Product:dispAll, page: 1 }
    requirements:
        page:  \d*

atelier_product_dispAllByCategory:
    pattern:  /{category}/{page}
    defaults: { _controller: AtelierProductBundle:Product:dispAllByCategory, page: 1 }
    requirements:
        page:  \d*
        category : \d+

atelier_product_disp_barcode:
    pattern:  /{id}/dispBarcode
    defaults: { _controller: AtelierProductBundle:Product:dispBarcode }
    requirements:
        id:  \d+
