atelier_appointement:
    resource: "@AtelierAppointementBundle/Resources/config/routing.yml"
    prefix:   /appointement
    
atelier_reservation:
    resource: "@AtelierReservationBundle/Resources/config/routing.yml"
    prefix:   /booking

atelier_user:
    resource: "@AtelierUserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/signup

atelier_index:
    resource: "@AtelierIndexBundle/Resources/config/routing.yml"
    prefix:   /

atelier_material:
    resource: "@AtelierMaterialBundle/Resources/config/routing.yml"
    prefix:   /material

atelier_product:
    resource: "@AtelierProductBundle/Resources/config/routing.yml"
    prefix:   /product

atelier_category:
    resource: "@AtelierCategoryBundle/Resources/config/routing.yml"
    prefix:   /category

