atelier_category:
    resource: "@AtelierCategoryBundle/Resources/config/routing.yml"
    prefix:   /category

atelier_user:
    resource: "@AtelierUserBundle/Resources/config/routing.yml"
    prefix:   /user

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

