atelier_user_index:
    pattern:  /
    defaults: { _controller: AtelierUserBundle:User:index }

atelier_user_editAdmin:
    pattern:  /{id}/edit
    defaults: { _controller: AtelierUserBundle:User:editAdmin }

atelier_user_list:
    pattern:  /list
    defaults: { _controller: AtelierUserBundle:User:list }

atelier_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: AtelierUserBundle:User:delete }

atelier_user_show:
    pattern:  /{id}/show
    defaults: { _controller: AtelierUserBundle:User:show }

atelier_user_addAdmin:
    pattern:  /{id}/addAdmin
    defaults: { _controller: AtelierUserBundle:User:addAdmin }

atelier_user_removeAdmin:
    pattern:  /{id}/removeAdmin
    defaults: { _controller: AtelierUserBundle:User:removeAdmin }
