atelier_user_index:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Profile:show }

atelier_user_editAdmin:
    pattern:  /{id}/edit
    defaults: { _controller: AtelierUserBundle:User:editAdmin }
    requirements:
        id:  \d+

atelier_user_list:
    pattern:  /list
    defaults: { _controller: AtelierUserBundle:User:list }

atelier_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: AtelierUserBundle:User:delete }
    requirements:
        id:  \d+
     
atelier_user_unregister:
    pattern:  /unregister
    defaults: { _controller: AtelierUserBundle:User:unregister }
        
        
atelier_user_show_my_profile:
    pattern:  /show
    defaults: { _controller: AtelierUserBundle:User:showMyProfile }

atelier_user_show:
    pattern:  /{id}/show
    defaults: { _controller: AtelierUserBundle:User:show }
    requirements:
        id:  \d+
        
atelier_user_addAdmin:
    pattern:  /{id}/addAdmin
    defaults: { _controller: AtelierUserBundle:User:addAdmin }
    requirements:
        id:  \d+
        
atelier_user_removeAdmin:
    pattern:  /{id}/removeAdmin
    defaults: { _controller: AtelierUserBundle:User:removeAdmin }
    requirements:
        id:  \d+
        
