parameters:
#    atelier_user.example.class: Atelier\UserBundle\Example

services:
#    atelier_user.example:
#        class: %atelier_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
