atelier_reservation_booking:
    pattern:  /
    defaults: { _controller: AtelierReservationBundle:Reservation:booking }

atelier_reservation_list:
    pattern:  /listAppointement/{page}
    defaults: { _controller: AtelierReservationBundle:Reservation:list , page : 1}

atelier_reservation_alllist:
    pattern:  /listAppointement
    defaults: { _controller: AtelierReservationBundle:Reservation:alllist , page : 1}

atelier_reservation_change:
    pattern:  /{id}/change
    defaults: { _controller: AtelierReservationBundle:Reservation:change }

atelier_reservation_delete:
    pattern:  /{id}/delete
    defaults: { _controller: AtelierReservationBundle:Reservation:delete }

atelier_reservation_disp_barcode:
    pattern:  /{id}/dispBarcode
    defaults: { _controller: AtelierReservationBundle:Reservation:dispBarcode }
