atelier_reservation_booking:
    pattern:  /
    defaults: { _controller: AtelierReservationBundle:Reservation:booking }

atelier_reservation_list:
    pattern:  /myBooking/{page}
    defaults: { _controller: AtelierReservationBundle:Reservation:list , page : 1}
    requirements:
        page:  \d*
        
atelier_reservation_alllist:
    pattern:  /allBooking/{page}
    defaults: { _controller: AtelierReservationBundle:Reservation:alllist , page : 1}
    requirements:
        page:  \d*
        
atelier_reservation_change:
    pattern:  /{id}/change
    defaults: { _controller: AtelierReservationBundle:Reservation:change }
    requirements:
        id:  \d+
        
atelier_reservation_delete:
    pattern:  /{id}/delete
    defaults: { _controller: AtelierReservationBundle:Reservation:delete }
    requirements:
        id:  \d+
        
atelier_reservation_disp_barcode:
    pattern:  /{id}/dispBarcode
    defaults: { _controller: AtelierReservationBundle:Reservation:dispBarcode }
    requirements:
        id:  \d+
        
atelier_reservation_products_by_category_id:
    pattern:  /productsByCategoryId
    defaults: { _controller: AtelierReservationBundle:Reservation:getByCategoryId }

atelier_reservation_materials_by_product_id:
    pattern:  /materialsByProductId
    defaults: { _controller: AtelierReservationBundle:Reservation:getByProductId }

atelier_reservation_materials_by_category_id:
    pattern:  /materialsByCategoryId
    defaults: { _controller: AtelierReservationBundle:Reservation:getMaterialByCategoryId }


